### PR TITLE
Confirmed friendship needs to be based on the existance of a '1 to 2' AND a '2 to 1' relation

### PR DESCRIPTION
**Pull request by githubertus**
Example of issue with old code:
1 has sent a friend request to 2
request is still pending and unconfirmed by 2, but 1 can already post on 2's wall

### CODE REVIEW

**Comment by lianglee** [comment]
Agree seems its a bug will merge soon

**Comment by githubertus** [comment]
A positive side effect: In a list like https://somesite.com/search?q=
we now can see the difference between
unconfirmed request -> shows 'Cancel Request'
and
confirmed request -> shows 'Unfriend'
Funny yes, the code has already been there for a long time, but 'Cancel Request' was never shown with the old logic.

**Comment by lianglee** [comment]
It should be following :

	return ossn_relation_exists($usera, $user2, 'friend:request') && ossn_relation_exists($user2, $usera, 'friend:request');

In commit its one & , but isn't it should be && between two ossn_relation_exists() ?

**Comment by githubertus** [comment]
Yes, you're right: it should be a logical AND (&&)
For some reason, bitwise AND was working here, too. But you're right. 👍

**Comment by lianglee** [comment]
We can simple utilize the 4th param of `ossn_relation_exists` ,  

    ossn_relation_exists(from, to, type,  true for cross check) 

This will result

    SELECT * FROM ossn_relationships as r JOIN ossn_relationships as r2 WHERE(r.relation_from='1' AND r.relation_to='2' AND r.type='friend:request' AND r2.relation_from='2' AND r2.relation_to='1' AND r2.type='friend:request') ;

**Pull request merged**
