### PR TITLE
Use same privacy logic as on main wall

### PR DESCRIPTION
**Pull request by githubertus**
or do you want a separate privacy setting for profile walls on admin backend?
see #1953

### CODE REVIEW

**Comment by lianglee** [comment]
With this users public posts will appear?

**Comment by lianglee** [comment]
I think  GetUserPosts need to be rewritten like getPublicPosts maybe cloning getPublicPosts and add owner_guid inside?

**Comment by githubertus** [comment]
For me it's working same way as on main wall now:

1. configure->wall-privacy set to friends-only
logged-off visitor => no posts visible
logged-on member && no friend => no posts visible
logged-on member && is friend => all posts visible
2. configure->wall-privacy set to public
logged-off visitor => only posts marked as 'public' are visible
logged-on member && no friend => only posts marked as 'public' are visible
logged-on member && is friend => all posts visible

**Comment by lianglee** [comment]
If you see components\OssnWall\plugins\default\wall\user\wall.php its trimming out posts if condition didn't match but pagination still shows same counts,  

This method is not realistic so we need to look into above as mentioned and change it accordingly

**Comment by githubertus** [comment]
Oh Yes, I see. 
And indeed the wrong counting already happens with old code before :))
because in the beginning all public and private and private records are returned and counted
and further down around line 65 friend-only records are sorted out if the conditions don't meet
so the original count is no more in sync ...
simple fix could be to add } else { count--;  below, if no friend condition meets

**Comment by lianglee** [comment]
User should see at least 10 posts in its more than 10,   Example

1. There are total 12 posts,   and on 1st page 10 friends posts.
2. Non friend should see remaining 2 posts.    

With current logic It only see 0 posts initially and remaining 2 if pagination xhr occurs.   I'll look into it this function today and see how far I can get it working and what are drawbacks.

**Pull request closed without merging**
