### PR TITLE
menu click bug fix #617

### LINKED ISSUE #617: small bug with menu
Need to add this in core . tab is not closing so user wont able to access the menus 
$('.ossn-topbar-dropdown-menu').click(function(){
			$('.ossn-notifications-box').hide();
});

screenshot from 2015-12-17 11 04 06

### PR DESCRIPTION
**Pull request by sathish4fri**
#617 bug fix

### CODE REVIEW

**Comment by githubertus** [comment]
works for me.
but wouldn't it make sense to make the hide() part of the drop-down menu code, instead of adding another event listener?

**Comment by sathish4fri** [comment]
it also do the same work thats . used the same functions

**Comment by lianglee** [comment]
@githubertus , yes i agree we should also add global hide function for dropdown.

@sathish4fri, its good that you used Ossn.NotificationBoxClose().

**Comment by githubertus** [comment]
Well, what I actually wanted to say: isn't it sufficiant to add Ossn.NotificationBoxClose() after line 305 of the core javascript lib? Because this handler 'knows' when the drop-down is opened and we won't need another one.

**Comment by lianglee** [comment]
@githubertus, yes, can you try and send pull request? i tried last time but wasn't able to add global function for dropdown.

**Comment by githubertus** [comment]
I had another look, and I think Sathis4fri's solution is the right one. Because the listener in core lib isn't used for goblue theme at all.

And since the notification box is part of the OssnNotifications module - and we don't have to close this box when this module is disabled.
Which is popping up a quite different problem I'll repport in a new thread. :)

Yeah, the deeper I look the more depencies I see ....
A. GoBlue
- the dropdown menue is handled by Bootstrap, NO listener in core lib needed, NO 'ossn-topbar-dropdown-menu-button' class in css
B. Oinitial
- 'ossn-topbar-dropdown-menu-button' class in css, the dropdown menue currently is handled by the listener in core lib

So I'd suggest to remove the 'ossn-topbar-dropdown-menu-button' listener from core lib, and make it part of the Oinitial script. We don't really need it globally.

**Comment by lianglee** [comment]
ossn-topbar-dropdown-menu-button is added in case someone wanted to apply some styling etc.

**Pull request merged**
