### PR TITLE
Update chat emoji

### PR DESCRIPTION
**Pull request by djbencrazy**
There is an entire update of emoji

### CODE REVIEW

**Comment by lianglee** [comment]
Thanks for pull request we shall verify it and will revert back to you.

**Comment by djbencrazy** [comment]
I would like to have done my job to get it done.

**Comment by djbencrazy** [comment]
When is this added?

**Comment by Lablnet** [comment]
i think no

**Comment by lianglee** [comment]
Hi @djbencrazy we shall add this in core within next release,  we are planning other things into release and shall merge your request soon.

**Comment by githubertus** [comment]
Basically working,
but there seems to be a problem with the javascript initialisation. Steps to reproduce:
1. Log in to Ossn
2. Choose chat partner from the list on the right
3. Open chat window at the bottom
4. Click smiley icon
--> No smiley list appearing
5. Keep chat window open and click on sitename in the header to force a page refresh
6. Open chat window at the bottom again
7. Click smiley icon
--> Smiley list opens now and smileys can be correctly selected

Tested with latest Firefox and Chrome on Win10 on newblue.ongolito.net

Besides of that: The smiley selector should be moved some pixels towards the top - it's overlapping the input field too much to my opnion.

**Comment by djbencrazy** [comment]
I have no problems. With this script.
Maybe you forgot to use code

**Comment by githubertus** [comment]
Hmm, that's strange ... So let me just tell what I did ...
I saw you made changes to the Smilies and the Chat component.
So without having a closer look into it, 
- I simply downloaded your complete reposititory
- I unpacked it lookally
- I copied your Smilies and Chat component onto my server.
Thus, my question - as this might be an explanation - : Can you confirm that your repository in fact includes all changes which are part of your pull request?

**Comment by djbencrazy** [comment]
I would like to test what a problem

**Comment by githubertus** [comment]
Well, in the meantime I verified your pull request is identical to your repository.
So, the problems is within your code.
You simply copied the logic from postings/comments, but the difference to the chat is:
When the home page is loaded for the first time, the element you are referencing is still not there.
That's why 
```
	if ($('.chat-container').length) {
		$('.chat-container').append('<div class="dropdown emojii-container-main"> <div class="emojii-container" data-active="emoticons"> <ul class="nav nav-tabs"></ul> </div> </div>');
	}

```
fails apppending the container.
The element is available not before the chat window is opened - but jquery's parsing is already done.
That' the reason it need's another page refresh - and that's no good.

**Comment by lianglee** [comment]
any update?

**Comment by djbencrazy** [comment]
have found a solution I hope this will be better

**Comment by djbencrazy** [comment]
will the callbacks succeed you think?

**Comment by githubertus** [comment]
Ok, I finally found the time to verify your changes again:
The issue I found in July is still the same: The emojis are unavailable with the initial page load.

**Comment by githubertus** [comment]
Thanks for spending your time on this tricky baby, djbencrazy.
But your patches are not working with newly opened chat boxes. Besides of that we're in a process of rewriting the complete Emoji script from scratch using only one globally available container.Thus, this pull request has become completely incompatible in the end and can be closed.

**Comment by lianglee** [comment]
Chat emoji has been added in v4.5

**Pull request closed without merging**
