### PR TITLE
Can use another db port

### PR DESCRIPTION
**Pull request by rodrigodemacedo**
Now you can connect the database to a different port instead the default. In the configuration file ("configurations/ossn.config.db.php"), just add \"$Ossn->port = '3310';\" or another port of your choice.

**This option was not adeed in the installation screen, only at the config file.**

### CODE REVIEW

**Comment by lianglee** [comment]
You also need to change installation files for this purpose.

**Comment by rodrigodemacedo** [comment]
I'm doing this now. And fixing the port on the installation screen too, accepting the "host:port"

**Comment by rodrigodemacedo** [comment]
Done

**Comment by rodrigodemacedo** [comment]
Why you don't have the master branch? And why the version isn't a tag and is a branch instead?

**Comment by lianglee** [comment]
Thanks for sending the pulls. For some reasons we don't keep master branch.

**Comment by rodrigodemacedo** [comment]
Thanks by accept my pull request. Now you don't need to create/modify the config file (configurations/ossn.config.db.php) to include the port as I said in the first comment of this pull request. Now if you specify the port in the host field at the instalation screen separated by ":" the installer understand the port and adds it to the config file automatically.

**Comment by lianglee** [comment]
Thanks for confirmation,  i shall go ahead and close the other ticket i created for checking.

👍

**Comment by rodrigodemacedo** [comment]
I think I have to test if the default port is working and set 3306 in the config file when someone gives a localhost, for example, without the port.
I will test (and fix if necessary) in two or three days.

**Pull request merged**
