### PR TITLE
display localized headline of component

### PR DESCRIPTION
**Pull request by githubertus**
<com_title> added in OssnAds and OssnSitePages

### CODE REVIEW

**Comment by lianglee** [comment]
We don't need to translate Component Name

**Comment by githubertus** [comment]
Hmmm, now that we got almost everything translated - why no translation here?

module-translation

**Comment by lianglee** [comment]
We are going to launch soon 'Components Project' on community site. And it will be difficult to find components in different languages.

**Comment by githubertus** [comment]
That's the point, and because of that my idea was to add the additional 'title' to the xml file.
This way the customer's search for interesting modules can rely on module name and module description in English as before. But on the other hand the programmer has a way to integrate his module perfectly into a running site with a different language. What I forgot, and what makes sense would be a fallback here: if title is set, display the title, if not, display the module name.

**Comment by lianglee** [comment]
Actually if there is no translation available for module name it is really not an issue as normal user has nothing to do with it (backend data).

Suppose i have created a a component and i only know English but don't know other languages. It would be a pain for other developers to translate their Component Names to other languages.

Ossn should show the name of component that is set in .xml file by owner.

**Pull request closed without merging**
