### PR TITLE
Add French language

### PR DESCRIPTION
**Pull request by ctlui**
Translated at 90%

### CODE REVIEW

**Comment by lianglee** [comment]
Can you please send us translation for components too?

**Comment by ctlui** [comment]
Hi,
Yes, just have to finalize some word and will be push, commit yesterday was just a mistake as my first use of GitHub :)

**Comment by sathish4fri** [comment]
:+1:

**Comment by moneya** [comment]
:+1:

**Comment by lianglee** [comment]
@ctlui , after completation, let us know, we'll put it on our components repository site.

I discussed with my team , from now onward we will upload different languages for Ossn on our community components repository.

**Comment by ctlui** [comment]
Hi,

All translation are done, even for component and installation.

**Comment by lianglee** [comment]
Thats good, 
Please create a French Language project on our community site (similar to : http://community.opensource-socialnetwork.org/component/view/376/hungarian-translations)

Thanks

**Pull request closed without merging**
