### PR TITLE
Update OssnPagination.php

### PR DESCRIPTION
**Pull request by Lablnet**
Avoid the error 
'"Division by zero" in file ..\opensource-socialnetwork\classes\OssnPagination.php (line 129)'

image

### CODE REVIEW

**Comment by githubertus** [comment]
I don't understand what it's for. I mean: the page_limit is set to 10 by default, and as long as you're not trying to twist it to 0 manually this case will be never reached.

**Comment by Lablnet** [comment]
@githubertus  are you sure?
I installed ossn by directly downloading form GitHub

And I saw this error in the error log file as shown in figure so why this error happens?

**Comment by githubertus** [comment]
No idea. Actually I'm running 5.0 RC extensively over the last month for testing and I never ran into this issue up to now.
Maybe you've installed any of your Malik 'specials'?
Try to track down on which page it happens, please.

**Comment by Lablnet** [comment]
Okay sure kindly give me time

**Comment by lianglee** [comment]
@Lablnet did you found the issue ? please provide details before closing the issue!.

**Pull request closed without merging**
