### PR TITLE
fix inbox update

### PR DESCRIPTION
**Pull request by githubertus**

### CODE REVIEW

**Comment by githubertus** [comment]
most likely this should be uncommented in messages.php, too.
(and the <div id="get-recent" style="display:none;"></div> is not needed anymore, I forgot)

**Comment by lianglee** [comment]
Recent messages at sidebar ? in messages page?

**Comment by githubertus** [comment]
inbox

**Comment by lianglee** [comment]
I didn't remember why i disabled this in v1.x

**Comment by githubertus** [comment]
perhaps because the javascript wasn't working? I uncommented the php first, but the old javascript didn't refresh the left column.

**Pull request closed without merging**
