### PR TITLE
Small fixes and a new theme

### PR DESCRIPTION
**Pull request by bishopgodsey**
This new theme is a green theme with more defined icons. All icons are
open source and public domain. I will be tweaking this theme over the
next few days, but it gives you an idea of where I am headed with it.
You need not commit it if you don't like it.

### CODE REVIEW

**Comment by sathish4fri** [comment]
did u created a new theme ? if yes please make it as new component

**Comment by bishopgodsey** [comment]
It is new and yes I created it. How would you like me to submit it? Is there a theme or component repository for third party components and themes?

**Comment by sathish4fri** [comment]
http://community.opensource-socialnetwork.org/components/all 
you can post your components here .. did u check with the community .

**Comment by bishopgodsey** [comment]
Thank you. If you want, you can kill this pull request and I will submit the theme at the community and resubmit the changes to the master with the fixes I had.

**Comment by sathish4fri** [comment]
sure @lianglee will close it .

**Pull request closed without merging**
