### PR TITLE
localization of passed time

### PR DESCRIPTION
**Pull request by robertito13**
clear code, supports trailing and leading text or none at all

### CODE REVIEW

**Comment by lianglee** [comment]
Is it working on german language?

**Comment by lianglee** [comment]
Your patch is working fine, We need to add 'site:timepassed:text' => 'Vor %s', in German language

@githubertus

**Comment by githubertus** [comment]
I'd leave it up to you, lianglee.
As you can see, 'Vor' is already part of 'site:timepassed' 

Robertito13 is right: his code looks cleaner from a translators point of view.
On the other hand, we should have in mind, that 'user_friendly_time()' will be one of the most often used functions in Ossn. And with my code ossn_print() is called only once, with robertitos code it has to be called twice. So in fact this is a decision of type 'cleaner versus faster'. 
My opionion: Instead of changing the current code, better write a 'translators wiki' explaining the special meaning of 'site:timepassed'. There are enough other critical parts like %s and the usage of ['] and ["] in the language file which are worth to be explained in a more detailed way.

**Comment by lianglee** [comment]
This pull request is merged manually thanks

**Pull request closed without merging**
