### PR TITLE
travis: PHP 5.5, 5.6 and 7.0 nightly added + few improvements

### PR DESCRIPTION
**Pull request by TomasVotruba**
- run PHPUnit
- no need to limit branches

### CODE REVIEW

**Comment by lianglee** [comment]
@TomasVotruba , thanks for pull request

**Comment by TomasVotruba** [comment]
:+1:

**Comment by lianglee** [comment]
We have to change it again, as Ossn didn't works on Php 5.6, build is fails on Travis.

**Comment by lianglee** [comment]
@TomasVotruba , can you check why builds is failing? . Also Ossn didn't work PHP 5.6

**Comment by TomasVotruba** [comment]
@lianglee Looks like there are no tests. Where are they located?

**Comment by lianglee** [comment]
@TomasVotruba , i just searched and it seems i lost that test files that my friend built it, can you help us in building simple test files? because i am completely unaware of travis, of my my friend did it but i lost his contact.

**Comment by TomasVotruba** [comment]
@lianglee Tests are pretty difficult to set up, depending on type of project. This looks like a standalone application not-OOP based, which is more difficult to test than standalone package.

I guess I can prepare some simple to test to show you example. Do you have some tip for small part to test?

**Comment by lianglee** [comment]
@TomasVotruba  , if you let me know how the tests works i can create it, TO be honest i don't know how to use travis, one of my friend knew but i loss his contact.

Do you know how tests works? i mean what are the things which need to be test? i maybe can prepare samll part to test then.

**Comment by TomasVotruba** [comment]
@lianglee I see. Travis runs test for you and ensures they are passing. The best would be showing on example test, that's why I ask.

You can start with test for issues here in Github. If something is broken, fix it and make sure it won't repeat again.

Yes, here is for example [single small test](https://github.com/ApiGen/Utils/blob/master/tests/ZipArchiveGeneratorTest.php) in my package.

**Comment by lianglee** [comment]
@Tomas, will check it thanks.

**Pull request merged**
