### PR TITLE
administrator language

### PR DESCRIPTION
**Pull request by sathish4fri**

### CODE REVIEW

**Comment by githubertus** [comment]
Sathish, I've spent hours with bringing English and German language files in line.
Before adding anything new, please grep carefully through ALL involved files to be absolutetely sure the string is not already in place. I'd like to get as few as possible changes, and 'Administrator' appears already on line 89.

**Comment by sathish4fri** [comment]
yes your right i close this

**Comment by githubertus** [comment]
Just realized: In a way you were right, too. :)
Yesterday, I was so much concentrated on only finding and replacing strings, that I did not take the time to have a look what your string was really meant for. Today, as I see it in the menu, I understand. And I would suggest to change your code to make use of "adminstration" instead of "admin", because you want to _adminstrate_ the site here. With 'administrator' people might think the link is leading to the adminitrators profile page.

BTW: Can you please tell me or send a screenshot on how to delete a branch on Github?

**Comment by sathish4fri** [comment]
You will be having deleted the brach option in right side of your branch . @githubertus  it will be shown only to admin  alone . others cant see the menu .

**Pull request closed without merging**
