### PR TITLE
Ossn Notification window enhacement

### PR DESCRIPTION
**Pull request by flochman**
Ossn Notification window enhacement to close window from click outside of notification window

### CODE REVIEW

**Comment by lianglee** [comment]
I just realized one thing:  One you click into any notification icon it didn't shows the loading notification box instead it take some time to complete ajax request and then show the complete box..

**Comment by flochman** [comment]
In both versions of enhacement code which I posted on OSSN forum?

**Comment by flochman** [comment]
This code should be rewriten to fit your needs:

`$('body').click(function() {
 +      $('.ossn-notifications-box').click(function(){
 +        $('.ossn-notifications-box').show();
 +         });
 +      $('.ossn-notifications-box').hide();
 +     });
 +	`

**Comment by lianglee** [comment]
I meant about your commit,  thanks for providing code i shall take a look and revert back to you.

**Pull request closed without merging**
