### PR TITLE
Added Sinhala Language (Sri Lankan Language)

### PR DESCRIPTION
**Pull request by Aroshana1**
I have added sinhala language to the project,

### CODE REVIEW

**Comment by lianglee** [comment]
Thanks can you also translate installation folder/locale ? Thanks for
translation

**Comment by Aroshana1** [comment]
ok  thank you for inform me. i will translate those page as well as  ,also if there any other thing need to do related to that translation let me know, thank you

**Comment by Aroshana1** [comment]
should i close this pull request  and  create  new pull request including  mentioned changes?

**Comment by lianglee** [comment]
You may edit current pull or close and push all together

**Pull request closed without merging**
