### PR TITLE
Call ossn_print for theme install error message

### PR DESCRIPTION
**Pull request by jjehannet**

### CODE REVIEW

**Comment by jjehannet** [comment]
It should be better to use the OssnFile getFileUploadError API to retrieve error message.
Without being too intrusive, it seems possible to change getFileUploadError into a static function.

screenshot-20150107192722

Are you interested in a new patch?

**Comment by lianglee** [comment]
Send us new patch if you can

**Comment by lianglee** [comment]
send us new patch if you can

**Comment by jjehannet** [comment]
Humm. A bit tited today.. I don't master github very well as you can see (extra merge...).
I changed the OssnFile::showFileUploadError to allow stack of messages.
On the other hand, if we keep the legacy redirect, the theme:install:error will never be printed.
Not sure what you prefer here.

**Comment by lianglee** [comment]
Thanks for Pull request will verify it soon and merge it

**Comment by lianglee** [comment]
Fixed

**Comment by lianglee** [comment]
Fixed

**Pull request closed without merging**
