### PR TITLE
Typo error Fixed and Account Settings url redirection fixed

### PR DESCRIPTION
**Pull request by samsruti**

### CODE REVIEW

**Comment by TheGameHHH** [comment]
You've forgot ossn.de.php file at Line 45.

**Comment by samsruti** [comment]
Oops .. I m fixing that one :+1:

**Comment by samsruti** [comment]
Now fixed :+1:

**Comment by ctlui** [comment]
Can you correct also module:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/search?utf8=%E2%9C%93&q=modlue&type=Code

**Comment by samsruti** [comment]
@ctlui , typo error fixed here : https://github.com/opensource-socialnetwork/opensource-socialnetwork/pull/569

**Pull request merged**
