### PR TITLE
set 'checked' according to current privacy setting

### PR DESCRIPTION
**Pull request by githubertus**

### CODE REVIEW

**Comment by githubertus** [comment]
!!! dont't merge, doesn't work either. still a timing problem! !!!
had an alert inside for debugging and it worked.
removed alert, and the buttons are not set :((

**Comment by githubertus** [comment]
Yeah, this is a tricky one.
The problem is 'async: true' in Ossn.PostRequest() called from the message box.

My inserted alert() gave Ajax enough time to complete and when I clicked the alert box, the buttons were ready and set up correctly.
Without alert, things run asynchronously, my code is executed too early and the radio buttons are not checked.
As a first workaround I surrounded my code with $(document).ajaxSuccess(function) { ...}
which in fact waits until the Ajax is completed and the buttons appeared correctly then. Fine!
But the big drawback is: the selector has to be 'document', and this way we're catching not only the Ajax call from the message box, but all notification ticker events, too. Not so fine.
So my idea is: To replace the hardcoded 'async: true' with 'async: $async' and set '$async = true' by default. This way, all other functions calling Ossn.PostRequest() will work as before.
Only Ossn.MessageBox() then has to pass an additional 'async: false' to Ossn.PostRequest() , the default 'true' will be overwritten and the problem is solved.

**Comment by githubertus** [comment]
Or perhaps simply add my code to the callback of Ossn.MessageBox() ?!?
Will check this tonight at home

**Comment by lianglee** [comment]
What if we call ossn.MessageBox at end?

**Comment by githubertus** [comment]
Well, there's another issue I wasn't aware of when I started to fix the message box for walls:
My inital idea was to remove the hardcoded 'checked' from system/templates/privacy and let jquery do the setting accordingly to the setting saved on the administrators page. Basically I got this working now, BUT: system/templates/privacy is used from 'add new photo album' too, this time relying on a hardcoded 'checked'. And here we'll end up with 2 unchecked buttons.
Yeah, and because I think there are much more important things to fix, it's not a good idea to close one issue and simultaneously open three new ones. So my conclusion would be not to touch anything of the core system right now, and instead put a copy of the button code into 'OssnWall\forms\privacy.php'. I'm going to try this right now and be back later.

**Comment by lianglee** [comment]
I have sent you PM. closing this pull request you can re open this pull request if you think its closed by misunderstanding

**Pull request closed without merging**
