### PR TITLE
added support for textareas

### PR DESCRIPTION
**Pull request by githubertus**
(and passing class to text)

### CODE REVIEW

**Comment by githubertus** [comment]
BEFORE MERGiNG:
please have a look into label handling. The logic is confusing me:
if label is true, the name? will be used - why that? why can't I pass a real Label?

In item.php of CustomFields it's even stranger:
if label is true, the placeholder will be used?!?

**Comment by lianglee** [comment]
Yes the logic is bit confusing , here is what i thought before i creating that , 
1. Label only used to tell if you wanted to show label or not.
2. Then the name of input element will be used as ossn_echo
-----

In custom fields 
1.  Actually i haven't touched item.php later but when i created custom fields i updated item.php a bit for custom fields.

The concept was user can enter the text of place holder from admin panel (when creating field) so we using it as label/placeholder. Because some site owners asked us they wanted to show placeholder as labels too because if you enter something in input field the placeholder disappear.


------
What we can do with label if someone wanted to pass label directly?

We may can do following : 

		if(isset($params['label']) && is_bool($params['label']) && $params['label'] === true){
				echo "<label>".ossn_print("{$item['name']}")."</label>";
		} elseif(isset($params['label']) &&  $params['label'] !== false){
				echo "<label>".$params['label']."</label>";
		}
		//if label is set true but haven't specified (actual) text then use item['name'] 
		//if it is specified but not true nor false then show actual label $params['label']

What you think?

**Comment by githubertus** [comment]
Yes, I can live with it:
no label or label = false -> nothing shown
label = true -> name is shown
label = string -> string is shown.

But I found a general bug: it's not **$params**['label'] but **$item**['label'] ... so I changed your code like

```
if(isset($item['label']) && is_bool($item['label']) && $item['label'] === true){
	echo "<label>".ossn_print("{$item['name']}")."</label>";
} elseif(isset($item['label']) &&  $item['label'] !== false){
	echo "<label>".$item['label']."</label>";
}

```

**Comment by lianglee** [comment]
Sure,  i haven't run above my code ... it was just quickly written lol

**Pull request merged**
